/**
 * ロトAI Ω∞ AUTONOMOUS — Scheduler
 * Auto-generates predictions on the day before each draw at 12:00
 *
 * Draw days: Monday (1) & Thursday (4)
 * Trigger:   Sunday 12:00 → for Monday draw
 *            Wednesday 12:00 → for Thursday draw
 */
var Scheduler = (function () {
  "use strict";

  var AUTO_HOUR = 12;
  var AUTO_MINUTE = 0;
  var DRAW_DAYS = [1, 4]; // Monday, Thursday
  var TRIGGER_DAYS = [0, 3]; // Sunday, Wednesday (day before draw)
  var CHECK_INTERVAL = 60000; // Check every 60 seconds
  var LAST_AUTO_KEY = "lotoai_last_auto";

  var _timerId = null;
  var _onAutoGenerate = null;
  var _statusEl = null;

  // ============================================================
  //  Date utilities
  // ============================================================

  function getNextDrawDate() {
    var now = new Date();
    var today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    for (var d = 1; d <= 7; d++) {
      var candidate = new Date(today.getTime() + d * 86400000);
      if (DRAW_DAYS.indexOf(candidate.getDay()) !== -1) return candidate;
    }
    return today;
  }

  function formatDate(d) {
    var y = d.getFullYear();
    var m = String(d.getMonth() + 1).padStart(2, "0");
    var dd = String(d.getDate()).padStart(2, "0");
    return y + "-" + m + "-" + dd;
  }

  function getTodayKey() {
    return formatDate(new Date());
  }

  // ============================================================
  //  Auto-trigger logic
  // ============================================================

  function shouldAutoGenerate() {
    var now = new Date();
    var dayOfWeek = now.getDay();
    var hour = now.getHours();
    var minute = now.getMinutes();

    // Must be a trigger day (day before draw)
    if (TRIGGER_DAYS.indexOf(dayOfWeek) === -1) return false;

    // Must be at or after the scheduled time
    if (hour < AUTO_HOUR) return false;
    if (hour === AUTO_HOUR && minute < AUTO_MINUTE) return false;

    // Check if already auto-generated today
    var lastAuto = null;
    try { lastAuto = localStorage.getItem(LAST_AUTO_KEY); } catch (e) { /* ignore */ }
    if (lastAuto === getTodayKey()) return false;

    return true;
  }

  function markAutoGenerated() {
    try {
      localStorage.setItem(LAST_AUTO_KEY, getTodayKey());
    } catch (e) { /* ignore */ }
  }

  function checkAndTrigger() {
    updateStatus();

    if (shouldAutoGenerate()) {
      markAutoGenerated();
      if (typeof _onAutoGenerate === "function") {
        _onAutoGenerate();
      }
    }
  }

  // ============================================================
  //  Status display
  // ============================================================

  function getNextAutoTime() {
    var now = new Date();
    var today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    // Find the next trigger day+time
    for (var d = 0; d <= 7; d++) {
      var candidate = new Date(today.getTime() + d * 86400000);
      if (TRIGGER_DAYS.indexOf(candidate.getDay()) !== -1) {
        var triggerTime = new Date(candidate);
        triggerTime.setHours(AUTO_HOUR, AUTO_MINUTE, 0, 0);

        if (triggerTime > now) {
          return triggerTime;
        }
      }
    }
    return null;
  }

  function getCountdown() {
    var next = getNextAutoTime();
    if (!next) return null;

    var diff = next.getTime() - Date.now();
    if (diff <= 0) return null;

    var hours = Math.floor(diff / 3600000);
    var minutes = Math.floor((diff % 3600000) / 60000);

    if (hours >= 24) {
      var days = Math.floor(hours / 24);
      hours = hours % 24;
      return days + "d " + hours + "h " + minutes + "m";
    }
    return hours + "h " + minutes + "m";
  }

  function updateStatus() {
    if (!_statusEl) _statusEl = document.getElementById("schedulerStatus");
    if (!_statusEl) return;

    var now = new Date();
    var dayOfWeek = now.getDay();
    var isTriggerDay = TRIGGER_DAYS.indexOf(dayOfWeek) !== -1;

    var lastAuto = null;
    try { lastAuto = localStorage.getItem(LAST_AUTO_KEY); } catch (e) { /* ignore */ }
    var alreadyGenerated = lastAuto === getTodayKey();

    var statusHTML = "";

    if (isTriggerDay && alreadyGenerated) {
      statusHTML = '<span class="sched-dot active"></span> AUTO PREDICTION COMPLETE';
    } else if (isTriggerDay && now.getHours() >= AUTO_HOUR) {
      statusHTML = '<span class="sched-dot pending"></span> AUTO TRIGGER PENDING...';
    } else {
      var countdown = getCountdown();
      if (countdown) {
        statusHTML = '<span class="sched-dot waiting"></span> NEXT AUTO: ' + countdown;
      } else {
        statusHTML = '<span class="sched-dot waiting"></span> SCHEDULER ACTIVE';
      }
    }

    _statusEl.innerHTML = statusHTML;
  }

  // ============================================================
  //  Start / Stop
  // ============================================================

  function start(onAutoGenerate) {
    _onAutoGenerate = onAutoGenerate;
    // Initial check
    checkAndTrigger();
    // Periodic check
    _timerId = setInterval(checkAndTrigger, CHECK_INTERVAL);
  }

  function stop() {
    if (_timerId) {
      clearInterval(_timerId);
      _timerId = null;
    }
  }

  // ============================================================
  //  Public API
  // ============================================================

  return {
    getNextDrawDate: getNextDrawDate,
    formatDate: formatDate,
    shouldAutoGenerate: shouldAutoGenerate,
    getCountdown: getCountdown,
    start: start,
    stop: stop,
    updateStatus: updateStatus
  };
})();
